homeassistant:
  name: Дом
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  packages: !include_dir_named packages/
  whitelist_external_dirs: /home/homeassistant/.homeassistant/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

lovelace:
  mode: yaml

config:

system_health:

conversation:

sun:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3

mobile_app:

automation: !include automation.yaml
script: !include script.yaml
input_boolean: !include input_boolean.yaml

# default_config:
# customize_glob:
# discovery:
# updater:
# map:
# cloud:
# history_graph:
