- platform: yeelight
  devices:
    192.168.1.x:
      name: hall_1
    192.168.1.x:
      name: hall_2
    192.168.1.x:
      name: livingroom_1
    192.168.1.x:
      name: livingroom_2
    192.168.1.x:
      name: kitchen
    192.168.1.x:
      name: bedroom
