- platform: dunehd
  host: 192.168.1.x

- platform: songpal
  endpoint: http://192.168.1.x:10000/sony

- platform: braviatv_psk
  host: 192.168.1.x
  psk: sony
  mac: 9x:xx:9x:xx:4x:xx
  amp: True
  android: False
  sourcefilter:
    - HDMI

- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  cache_path: /home/homeassistant/.homeassistant/spotify_cache/.spotify-token-cache_user_1

- platform: spotify
  client_id: !secret spotify_client_id_2
  client_secret: !secret spotify_client_secret_2
  cache_path: /home/homeassistant/.homeassistant/spotify_cache/.spotify-token-cache_user_2

- platform: spotify
  client_id: !secret spotify_client_id_3
  client_secret: !secret spotify_client_secret_3
  cache_path: /home/homeassistant/.homeassistant/spotify_cache/.spotify-token-cache_user_3
