# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.livingroom_1:
      friendly_name: Зал Люстра
      icon: mdi:ceiling-light
    light.livingroom_2:
      friendly_name: Зал Ночник
    light.window_livingroom:
      friendly_name: Зал Окно
      icon: mdi:lamp


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: livingroom_1
    192.168.1.x:
      name: livingroom_2


# Таймеры
timer:
  livingroom_1:
    duration: '03:00:00'
  livingroom_2:
    duration: '03:00:00'


# Вкл / выкл автоматизации освещения в Lovelace
input_boolean:
  livingroom_automation:
    name: Зал
    initial: on
    icon: mdi:home-automation


# Автоматизации
automation:
  # Включение люстры по одинарному клику
  - alias: livingroom_1_light_on_switch_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1002
    condition:
      - condition: state
        entity_id: light.livingroom_1
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.livingroom_1
        data_template:
          brightness_pct: >
            {% if now().hour >= 0 and now().hour < 8 %} 10
            {% elif now().hour >= 8 and now().hour < 21 %} 100
            {% elif now().hour >= 21 and now().hour < 22 %} 50
            {% elif now().hour >= 22 and now().hour < 24 %} 1
            {% endif %}
          color_temp: 250


  # Выключение люстры по одинарному клику
  - alias: livingroom_1_light_off_switch_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1002
    condition:
      - condition: state
        entity_id: light.livingroom_1
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.livingroom_1


  # Включение ночника по двойному клику
  - alias: livingroom_2_light_on_switch_double_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1004
    condition:
      - condition: state
        entity_id: light.livingroom_2
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.livingroom_2
        data_template:
          brightness_pct: >
            {% if now().hour >= 0 and now().hour < 8 %} 10
            {% elif now().hour >= 8 and now().hour < 21 %} 100
            {% elif now().hour >= 21 and now().hour < 24 %} 10
            {% endif %}
          color_temp: 250


  # Выключение ночника по двойному клику
  - alias: livingroom_2_light_off_switch_double_click
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1004
    condition:
      - condition: state
        entity_id: light.livingroom_2
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.livingroom_2


  # Включение группы по длинному нажатию
  - alias: livingroom_group_light_on_switch_long_press
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1001
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.livingroom_1
                state: 'off'
              - condition: state
                entity_id: light.livingroom_2
                state: 'off'
          - condition: or
            conditions:
              - condition: state
                entity_id: light.livingroom_1
                state: 'off'
              - condition: state
                entity_id: light.livingroom_2
                state: 'off'
    action:
      - service: light.turn_on
        entity_id:
          - light.livingroom_1
          - light.livingroom_2
        data_template:
          brightness_pct: 100
          color_temp: 250


  # Выключение группы по длинному нажатию
  - alias: livingroom_group_light_off_switch_long_press
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
          event: 1001
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.livingroom_1
            state: 'on'
          - condition: state
            entity_id: light.livingroom_2
            state: 'on'
    action:
      - service: light.turn_off
        entity_id:
          - light.livingroom_1
          - light.livingroom_2


  # Запуск таймера при любом нажатии
  - alias: livingroom_timer
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.event in [1002,1001,1004] }}"
    action:
      - service: timer.cancel
        data_template:
          entity_id: >
            {% if trigger.event.data.event == 1002 %}
              timer.livingroom_1
            {% elif trigger.event.data.event == 1004 %}
              timer.livingroom_2
            {% elif trigger.event.data.event == 1001 %}
              timer.livingroom_1, timer.livingroom_2
            {% endif %}
      - service: timer.start
        data_template:
          entity_id: >
            {% if trigger.event.data.event == 1002 %}
              timer.livingroom_1
            {% elif trigger.event.data.event == 1004 %}
              timer.livingroom_2
            {% elif trigger.event.data.event == 1001 %}
              timer.livingroom_1, timer.livingroom_2
            {% endif %}


  # Выключение после остановки таймера
  - alias: livingroom_light_off_timer
    initial_state: true
    trigger:
      - platform: event
        event_type: timer.finished
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.motion_sensor_livingroom
            state: 'off'
            for:
              minutes: 10
          - condition: template
            value_template: "{{ trigger.event.data.entity_id in ['timer.livingroom_1','timer.livingroom_2'] }}"
          - condition: or
            conditions:
              - condition: state
                entity_id: light.livingroom_1
                state: 'on'
              - condition: state
                entity_id: light.livingroom_2
                state: 'on'
    action:
      - service: light.turn_off
        data_template:
          entity_id: >
            {% if trigger.event.data.entity_id == 'timer.livingroom_1' %}
              light.livingroom_1
            {% elif trigger.event.data.entity_id == 'timer.livingroom_2' %}
              light.livingroom_2
            {% endif %}


  # Включение ночника в заданное время при низкой освещенности
  - alias: livingroom_2_light_on
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.outdoor_illuminance') | int < 1000 }}"
    condition:
      - condition: and
        conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunset
                after_offset: "-00:30:00"
              - condition: time
                before: '22:50:00'
          - condition: state
            entity_id: light.livingroom_2
            state: 'off'
          - condition: state
            entity_id: timer.livingroom_2
            state: 'idle'
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: 'disarmed'
    action:
      - service: light.turn_on
        entity_id: light.livingroom_2
        data_template:
          brightness_pct: 5
          color_temp: 250
          transition: 3


  # Включение ночника на окне в заданное время при низкой освещенности
  - alias: livingroom_window_light_on
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ states('sensor.outdoor_illuminance') | int < 1000 }}"
    condition:
      - condition: and
        conditions:
          - condition: and
            conditions:
              - condition: sun
                after: sunset
                after_offset: "-00:30:00"
              - condition: time
                before: '22:50:00'
          - condition: state
            entity_id: light.window_livingroom
            state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.window_livingroom
        data_template:
          brightness_pct: 50


  # Выключение в заданное время
  - alias: livingroom_light_off
    initial_state: true
    trigger:
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '23:00:05'
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: light.livingroom_2
            state: 'on'
          - condition: state
            entity_id: light.window_livingroom
            state: 'on'
    action:
      - service: light.turn_off
        data_template:
          entity_id: >
            {% if is_state('light.livingroom_2', 'on') and is_state('timer.livingroom_2', 'idle') %}
              light.livingroom_2
            {% elif is_state('light.window_livingroom', 'on') %}
              light.window_livingroom
            {% endif %}


  # Уменьшение яркости в заданное время
  - alias: livingroom_light_decrease
    initial_state: true
    trigger:
      - platform: time
        at: '21:30:00'
      - platform: time
        at: '21:30:05'
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.livingroom_1
                state: 'on'
              - condition: template
                value_template: "{{ (state_attr('light.livingroom_1', 'brightness') | int) > 25 }}"
          - condition: and
            conditions:
              - condition: state
                entity_id: light.window_livingroom
                state: 'on'
              - condition: template
                value_template: "{{ (state_attr('light.window_livingroom', 'brightness') | int) > 25 }}"
    action:
      - service: light.turn_on
        data_template:
          entity_id: >
            {% if is_state('light.livingroom_1', 'on') and is_state('timer.livingroom_2', 'idle') %}
              light.livingroom_1
            {% elif is_state('light.window_livingroom', 'on')  %}
              light.window_livingroom
            {% endif %}
          brightness_pct: 25


  # Включение / выключение автоматизации переключателем в Lovelace
  - alias: livingroom_automation_on_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.livingroom_automation
    action:
      - service: timer.cancel
        entity_id:
          - timer.livingroom_1
          - timer.livingroom_2
      - service_template: >
          {% if is_state('input_boolean.livingroom_automation', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        entity_id:
          - automation.livingroom_timer
          - automation.livingroom_light_off_timer
          - automation.livingroom_2_light_on
          - automation.livingroom_light_off
          - automation.window_livingroom_light_on
          - automation.livingroom_light_decrease
