# Кастомизация
homeassistant:
  customize:
    # Сцены освещения
    scene.bright_livingroom:
      friendly_name: Ярко
      icon: mdi:brightness-7
    scene.movie_livingroom:
      friendly_name: Кино
      icon: mdi:movie-roll
    scene.night_light_livingroom:
      friendly_name: Ночник
      icon: mdi:weather-night
    scene.light_off_livingroom:
      friendly_name: Выкл.
      icon: mdi:lightbulb-outline


# Сцены освещения
scene:
  # Ярко
  - name: bright_livingroom
    entities:
      light.livingroom_1:
        state: on
        brightness_pct: 100
        color_temp: 250
        transition: 3
      light.livingroom_2:
        state: on
        brightness_pct: 100
        color_temp: 250
        transition: 3

  # Кино
  - name: movie_livingroom
    entities:
      light.livingroom_2:
        state: on
        brightness_pct: 15
        rgb_color: [102, 102, 255]
        transition: 3
      light.livingroom_1:
        state: off
        transition: 3

  # Ночник
  - name: night_light_livingroom
    entities:
      light.livingroom_2:
        state: on
        brightness_pct: 1
        color_temp: 588
        transition: 3
      light.livingroom_1:
        state: off
        transition: 3

  # Выключение света в зале
  - name: light_off_livingroom
    entities:
      light.livingroom_1:
        state: off
        transition: 3
      light.livingroom_2:
        state: off
        transition: 3
      light.window_livingroom:
        state: off
        transition: 3

  # Включение сцены Паника
  - name: panic_light_on
    entities:
      light.hall_1:
        state: on
        effect: Strobe epilepsy!
      light.hall_2:
        state: on
        effect: Strobe epilepsy!
      light.livingroom_1:
        state: on
        effect: Strobe epilepsy!
      light.livingroom_2:
        state: on
        effect: Strobe epilepsy!
      light.kitchen:
        state: on
        effect: Strobe epilepsy!
      light.bedroom:
        state: on
        effect: Strobe epilepsy!

  # Выключение сцены Паника
  - name: panic_light_off
    entities:
      light.hall_1:
        state: on
        effect: Stop
      light.hall_2:
        state: on
        effect: Stop
      light.livingroom_1:
        state: on
        effect: Stop
      light.livingroom_2:
        state: on
        effect: Stop
      light.kitchen:
        state: on
        effect: Stop
      light.bedroom:
        state: on
        effect: Stop
