group:
 # Вкл / выкл автоматизаций освещения
 light_automation:
   name: Автоматизация освещения
   entities:
     - input_boolean.hall_automation
     - input_boolean.livingroom_automation
     - input_boolean.kitchen_automation
     - input_boolean.bedroom_automation
     - input_boolean.bathroom_automation
