- alias: Fake Presence
  initial_state: true
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: sun
              after: sunset
              after_offset: '-01:30:00'
            - condition: time
              before: '23:00:00'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_away
  action:
    - condition: state
      entity_id: script.fake_presence
      state: 'off'
    - service: script.turn_on
      entity_id: script.fake_presence_on
