- alias: Fake Presence
  initial_state: true
  trigger:
    - platform: template
      value_template: "{% if is_state('device_tracker.host_1', 'not_home')
                         and is_state('device_tracker.host_2', 'not_home')
                         and is_state('device_tracker.host_3', 'not_home') %}
                         true
                       {% endif %}"
    - platform: sun
      event: sunset
      offset: '-01:30:00'
    - platform: event
      event_type: event_fake_presence
  condition:
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: sun
              after: sunset
              after_offset: '-01:30:00'
            - condition: time
              before: '23:00:00'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: armed_away
  action:
    - service: light.turn_on
      data_template:
        entity_id: >
          {{ ['light.kitchen','light.livingroom_1','light.bedroom'] | random }}
        brightness_pct: 100
        color_temp: 250
    - delay: '00:{{ (range(2, 15) | random) }}:00'
    - service_template: >
        {% if is_state('alarm_control_panel.ha_alarm', 'armed_away') %}
          light.turn_off
        {% else %}
          light.turn_on
        {% endif %}
    - delay: '00:00:{{ (range(1, 10) | random) }}'
    - event: event_fake_presence
