# ------------------------------------------------------------------------------
# - Включение люстры по одинарному клику
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Click Light On
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: single
  condition:
    - condition: state
      entity_id: light.livingroom_1
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.livingroom_1
      data_template:
        brightness_pct: >
          {% set h = now().strftime('%H') | int %}
            {% if h >= 0 and h < 8 %}
              10
            {% elif h >= 8 and h < 21 %}
              100
            {% elif h >= 21 and h < 22 %}
              50
            {% elif h >= 22 and h < 24 %}
              10
          {% endif %}
        color_temp: 250
    - service: timer.cancel
      entity_id: timer.livingroom_1
    - service: timer.start
      entity_id: timer.livingroom_1

# ------------------------------------------------------------------------------
# - Выключение люстры по одинарному клику
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Click Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: single
  condition:
    - condition: state
      entity_id: light.livingroom_1
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.livingroom_1
    - service: timer.cancel
      entity_id: timer.livingroom_1
    - service: timer.start
      entity_id: timer.livingroom_1

# ------------------------------------------------------------------------------
# - Включение ночника по по двойному клику
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Double Click Night Light On
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: double
  condition:
    - condition: state
      entity_id: light.livingroom_2
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.livingroom_2
      data_template:
        brightness_pct: >
          {% set h = now().strftime('%H') | int %}
            {% if h >= 0 and h < 8 %}
              10
            {% elif h >= 8 and h < 21 %}
              100
            {% elif h >= 21 and h < 22 %}
              10
            {% elif h >= 22 and h < 24 %}
              10
          {% endif %}
        color_temp: 250
    - service: timer.cancel
      entity_id: timer.livingroom_2
    - service: timer.start
      entity_id: timer.livingroom_2

# ------------------------------------------------------------------------------
# - Выключение ночника по по двойному клику
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Doble Click Night Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: double
  condition:
    - condition: state
      entity_id: light.livingroom_2
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.livingroom_2
    - service: timer.cancel
      entity_id: timer.livingroom_2
    - service: timer.start
      entity_id: timer.livingroom_2

# ------------------------------------------------------------------------------
# - Включение группы по длинному нажатию
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Long Click Group Light On
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: long_click_press
  condition:
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: light.livingroom_1
              state: 'off'
            - condition: state
              entity_id: light.livingroom_2
              state: 'off'
        - condition: or
          conditions:
            - condition: state
              entity_id: light.livingroom_1
              state: 'off'
            - condition: state
              entity_id: light.livingroom_2
              state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.livingroom_1
        - light.livingroom_2
      data_template:
        brightness_pct: 100
        color_temp: 250
    - service: timer.cancel
      entity_id:
        - timer.livingroom_1
        - timer.livingroom_2
    - service: timer.start
      entity_id:
        - timer.livingroom_1
        - timer.livingroom_2

# ------------------------------------------------------------------------------
# - Выключение группы по длинному нажатию
# ------------------------------------------------------------------------------
- alias: Livingroom Switch Long Click Group Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d00010f2389
        click_type: long_click_press
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: light.livingroom_1
          state: 'on'
        - condition: state
          entity_id: light.livingroom_2
          state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.livingroom_1
        - light.livingroom_2
    - service: timer.cancel
      entity_id:
        - timer.livingroom_1
        - timer.livingroom_2
    - service: timer.start
      entity_id:
        - timer.livingroom_1
        - timer.livingroom_2

# ------------------------------------------------------------------------------
# - Выключение группы после остановки таймера
# ------------------------------------------------------------------------------
- alias: Livingroom Group Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id:
          - timer.livingroom_1
          - timer.livingroom_2
  action:
    - condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.motion_sensor_158d0001108772
          state: 'off'
          for:
            minutes: 1
        - condition: state
          entity_id: light.livingroom_1
          state: 'on'
        - condition: state
          entity_id: light.livingroom_2
          state: 'on'
    - service: light.turn_off
      entity_id:
        - light.livingroom_1
        - light.livingroom_2

# ------------------------------------------------------------------------------
# - Включение / Выключение автоматизации переключателем в GUI
# ------------------------------------------------------------------------------
- alias: Livingroom Automation ON_OFF Manual
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_auto_status
  action:
    - service: timer.cancel
      entity_id:
        - timer.livingroom_1
        - timer.livingroom_2
    - service_template: >
        {% if is_state('input_boolean.livingroom_auto_status', 'on') %}
          automation.turn_on
        {% else %}
          automation.turn_off
        {% endif %}
      entity_id:
#        - automation.livingroom_reset_timer
        - automation.livingroom_group_light_off
        - automation.livingroom_light_dimming
        - automation.livingroom_timer_night_light_on
        - automation.livingroom_timer_night_light_off

# ------------------------------------------------------------------------------
# - Изменение яркости в заданное время
# ------------------------------------------------------------------------------
- alias: Livingroom Light Dimming
  initial_state: true
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: light.livingroom_1
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.livingroom_1
      data_template:
        brightness_pct: 25
        color_temp: 250

# ------------------------------------------------------------------------------
# - Включение ночника в заданное время
# ------------------------------------------------------------------------------
- alias: Livingroom Timer Night Light On
  initial_state: true
  trigger:
    - platform: time
      minutes: '/5'
      seconds: 00
  condition:
    - condition: and
      conditions:
        - condition: and
          conditions:
            - condition: sun
              after: sunset
              after_offset: "-01:00:00"
            - condition: time
              before: '22:50:00'
        - condition: state
          entity_id: timer.livingroom_2
          state: 'idle'
        - condition: state
          entity_id: light.livingroom_2
          state: 'off'
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: disarmed
  action:
    - service: light.turn_on
      entity_id: light.livingroom_2
      data_template:
        brightness_pct: 10
        color_temp: 250

# ------------------------------------------------------------------------------
# - Выключение ночника в заданное время
# ------------------------------------------------------------------------------
- alias: Livingroom Timer Night Light Off
  initial_state: true
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: timer.livingroom_2
          state: 'idle'
        - condition: state
          entity_id: light.livingroom_2
          state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.livingroom_2
