# ------------------------------------------------------------------------------
# - Запустить Кинозал 1
# ------------------------------------------------------------------------------
- alias: dfi on 1
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.dfi
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'off'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.dunehd_on_sonytv_on_hdmi2
    - delay: 00:00:15
    - service: script.turn_on
      entity_id: script.run_dfi
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.ott_club
        - input_boolean.kinopub

# ------------------------------------------------------------------------------
# - Запустить Кинозал 2
# ------------------------------------------------------------------------------
- alias: dfi on 2
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.dfi
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'on'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.dunehd
    - delay: 00:00:03
    - service: script.turn_on
      entity_id: script.run_dfi
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.ott_club
        - input_boolean.kinopub

# ------------------------------------------------------------------------------
# - Запустить Кинозал 3
# ------------------------------------------------------------------------------
- alias: dfi on 3
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.dfi
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.dune_status
          state: 'Menu'
        - condition: state
          entity_id: sensor.dune_status
          state: 'OTT Club'
        - condition: state
          entity_id: sensor.dune_status
          state: 'Kinopub'
  action:
    - service: script.turn_on
      entity_id: script.run_dfi
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.ott_club
        - input_boolean.kinopub
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'off'
    - service: media_player.turn_on
      entity_id: media_player.sony_bravia_tv

# ------------------------------------------------------------------------------
# - Вкл / Выкл Кинозал в homekit
# ------------------------------------------------------------------------------
- alias: dfi switch on off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dune_status
  action:
    - service_template: >
        {% if is_state('sensor.dune_status', 'DFI') %}
           input_boolean.turn_on
         {% else %}
           input_boolean.turn_off
         {% endif %}
      entity_id: input_boolean.dfi

# ------------------------------------------------------------------------------
# - Запустить OTT Club 1
# ------------------------------------------------------------------------------
- alias: ott club on 1
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.ott_club
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'off'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.dunehd_on_sonytv_on_hdmi2
    - delay: 00:00:15
    - service: script.turn_on
      entity_id: script.run_ott_club
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.kinopub

# ------------------------------------------------------------------------------
# - Запустить OTT Club 2
# ------------------------------------------------------------------------------
- alias: ott club on 2
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.ott_club
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'on'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.dunehd
    - delay: 00:00:03
    - service: script.turn_on
      entity_id: script.run_ott_club
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.kinopub

# ------------------------------------------------------------------------------
# - Запустить OTT Club 3
# ------------------------------------------------------------------------------
- alias: ott club on 3
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.ott_club
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.dune_status
          state: 'Menu'
        - condition: state
          entity_id: sensor.dune_status
          state: 'DFI'
        - condition: state
          entity_id: sensor.dune_status
          state: 'Kinopub'
  action:
    - service: script.turn_on
      entity_id: script.run_ott_club
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.kinopub
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'off'
    - service: media_player.turn_on
      entity_id: media_player.sony_bravia_tv

# ------------------------------------------------------------------------------
# - Вкл / Выкл OTT Club в homekit
# ------------------------------------------------------------------------------
- alias: ott club switch on off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dune_status
  action:
    - service_template: >
        {% if is_state('sensor.dune_status', 'OTT Club') %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.ott_club

# ------------------------------------------------------------------------------
# - Запустить Kinopub 1
# ------------------------------------------------------------------------------
- alias: kinopub on 1
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.kinopub
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'off'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.dunehd_on_sonytv_on_hdmi2
    - delay: 00:00:15
    - service: script.turn_on
      entity_id: script.run_kinopub
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.ott_club

# ------------------------------------------------------------------------------
# - Запустить Kinopub 2
# ------------------------------------------------------------------------------
- alias: kinopub on 2
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.kinopub
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: media_player.sony_bravia_tv
          state: 'on'
        - condition: state
          entity_id: media_player.dunehd
          state: 'off'
  action:
    - service: media_player.turn_on
      entity_id: media_player.dunehd
    - delay: 00:00:03
    - service: script.turn_on
      entity_id: script.run_kinopub
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.ott_club

# ------------------------------------------------------------------------------
# - Запустить Kinopub 3
# ------------------------------------------------------------------------------
- alias: ott club on 3
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.kinopub
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.dune_status
          state: 'Menu'
        - condition: state
          entity_id: sensor.dune_status
          state: 'DFI'
        - condition: state
          entity_id: sensor.dune_status
          state: 'OTT Club'
  action:
    - service: script.turn_on
      entity_id: script.run_kinopub
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.dfi
        - input_boolean.ott_club
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'off'
    - service: media_player.turn_on
      entity_id: media_player.sony_bravia_tv

# ------------------------------------------------------------------------------
# - Вкл / Выкл Kinopub в homekit
# ------------------------------------------------------------------------------
- alias: kinopub switch on off
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.dune_status
  action:
    - service_template: >
        {% if is_state('sensor.dune_status', 'Kinopub') %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.kinopub

# ------------------------------------------------------------------------------
# - После выключения ТВ, выключить Dune HD
# ------------------------------------------------------------------------------
- alias: dunehd off after sonytv off
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.dunehd_off

# ------------------------------------------------------------------------------
# - После включения саундбара, установить громкость на 15
# ------------------------------------------------------------------------------
- alias: sony htnt5 on volume 10
  initial_state: true
  trigger:
    - platform: state
      entity_id: media_player.sony_htnt5
      to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.sony_htnt5
        volume_level: 0.15
