# ------------------------------------------------------------------------------
# - Потребление за месяц
# ------------------------------------------------------------------------------
- alias: power
  initial_state: true
  trigger:
    - platform: time
      seconds: '/30'
  action:
    - service: mqtt.publish
      data_template:
        topic: "power/plug1/month"
        payload: "{{ (states('sensor.power_mqtt_month_plug1') | float +
                     (states('sensor.load_switch_plug_158d0001003f15') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/plug_camera/month"
        payload: "{{ (states('sensor.power_mqtt_month_plug_camera') | float +
                     (states('sensor.load_switch_plug_158d00011016d0') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_hall_1/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_hall_1') | float +
                     (states('sensor.load_light_hall_1') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_hall_2/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_hall_2') | float +
                     (states('sensor.load_light_hall_2') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_livingroom_1/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_livingroom_1') | float +
                     (states('sensor.load_light_livingroom_1') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_livingroom_2/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_livingroom_2') | float +
                     (states('sensor.load_light_livingroom_2') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_kitchen/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_kitchen') | float +
                     (states('sensor.load_light_kitchen') | float /120000)) | round(5) }}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_bedroom/month"
        payload: "{{ (states('sensor.power_mqtt_month_light_bedroom') | float +
                     (states('sensor.load_light_bedroom') | float /120000)) | round(5) }}"
        retain: true

# ------------------------------------------------------------------------------
# - Общее потребление за месяц
# ------------------------------------------------------------------------------
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "power/month_total"
        payload: "{{ (states('sensor.power_mqtt_month_plug1') | float +
                      states('sensor.power_mqtt_month_plug_camera') | float +
                      states('sensor.power_mqtt_month_light_hall_1') | float +
                      states('sensor.power_mqtt_month_light_hall_2') | float +
                      states('sensor.power_mqtt_month_light_livingroom_1') | float +
                      states('sensor.power_mqtt_month_light_livingroom_2') | float +
                      states('sensor.power_mqtt_month_light_kitchen') | float +
                      states('sensor.power_mqtt_month_light_bedroom') | float) | round(3) }}"
        retain: true
    - delay: 00:00:02
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/{{ now().month }}"
        payload: "{{ (states('sensor.power_mqtt_total_month') | float) | round(3) }}"
        retain: true

# ------------------------------------------------------------------------------
# - Общее потребление за год
# ------------------------------------------------------------------------------
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "power/year_total"
        payload: "{{ (states('sensor.power_mqtt_total_m1') | float + states('sensor.power_mqtt_total_m2') | float +
                      states('sensor.power_mqtt_total_m3') | float + states('sensor.power_mqtt_total_m4') | float +
                      states('sensor.power_mqtt_total_m5') | float + states('sensor.power_mqtt_total_m6') | float +
                      states('sensor.power_mqtt_total_m7') | float + states('sensor.power_mqtt_total_m8') | float +
                      states('sensor.power_mqtt_total_m9') | float + states('sensor.power_mqtt_total_m10') | float +
                      states('sensor.power_mqtt_total_m11') | float + states('sensor.power_mqtt_total_m12') | float) | round(3) }}"
        retain: true

# ------------------------------------------------------------------------------
# - Новый месяц, обнуление счетчиков в группе "Потребление за месяц"
# ------------------------------------------------------------------------------
- alias: power new month
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:15'
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "power/plug1/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/plug_camera/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_hall_1/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_hall_2/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_livingroom_1/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_livingroom_2/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_kitchen/month"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/light_bedroom/month"
        payload: '{{ 0.0 }}'
        retain: true

# ------------------------------------------------------------------------------
# - Конец года, сохранение общего потребления в отдельный топик
# ------------------------------------------------------------------------------
- alias: power old year
  initial_state: true
  trigger:
    - platform: time
      at: '23:59:30'
  condition:
    - condition: template
      value_template: "{{ now().month == 12 and now().day == 31 }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "power/year_total/{{ now().year }}"
        payload: "{{ (states('sensor.power_mqtt_total_year') | float) | round(3) }}"
        retain: true

# ------------------------------------------------------------------------------
# - Новый год, обнуление счетчиков в группе "Общее потребление"
# ------------------------------------------------------------------------------
- alias: power new year
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:20'
  condition:
    - condition: template
      value_template: "{{ now().month == 1 and now().day == 1 }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/1"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/2"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/3"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/4"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/5"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/6"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/7"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/8"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/9"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/10"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/11"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/month_total/12"
        payload: '{{ 0.0 }}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/year_total"
        payload: '{{ 0.0 }}'
        retain: true
