# ------------------------------------------------------------------------------
# - Датчики температуры Low
# ------------------------------------------------------------------------------
- alias: push_low_temp_livingroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001140c6a
      above: 29
      below: 35
    - platform: numeric_state
      entity_id: sensor.command_sensor
      above: 60
      below: 70
  action:
    - service: notify.pushover
      data_template:
        title: "{{ trigger.from_state.name }}!"
        message: >
          {% if trigger.from_state.name == 'Зал Температура' %}
            {{ states.sensor.temperature_158d0001140c6a.state }}°C !
          {% elif trigger.from_state.name == 'Температура' %}
            Raspberry {{ states.sensor.command_sensor.state }}°C !
          {% endif %}
        data:
          device: iphone
          sound: siren
          priority: 0

# ------------------------------------------------------------------------------
# - Датчики температуры High
# ------------------------------------------------------------------------------
- alias: push_high_temp_livingroom
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperature_158d0001140c6a
      above: 35
    - platform: numeric_state
      entity_id: sensor.command_sensor
      above: 70
  action:
    - service: notify.pushover
      data_template:
        title: "{{ trigger.from_state.name }}!"
        message: >
          {% if trigger.from_state.name == 'Зал Температура' %}
            {{ states.sensor.temperature_158d0001140c6a.state }}°C !
          {% elif trigger.from_state.name == 'Температура' %}
            Raspberry {{ states.sensor.command_sensor.state }}°C !
          {% endif %}
        data:
          device: iphone
          sound: persistent
          priority: 2
          retry: 30
          expire: 600

# ------------------------------------------------------------------------------
# - Состояние батареи датчиков
# ------------------------------------------------------------------------------
- alias: push_low_battery
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: >
          {% set threshold = 10 %}
            {% for item in states.sensor if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
              {% if loop.first %}
                {{ true }}
              {% endif %}
            {% endfor %}
      - condition: template
        value_template: >
          {% set threshold = 10 %}
            {% for item in states.binary_sensor if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
              {% if loop.first %}
                {{ true }}
              {% endif %}
            {% endfor %}
  action:
    - service: notify.pushover
      data_template:
        title: "Низкий уровень заряда!"
        message: >
          {% set threshold = 10 %}
          {% set domains = [states.binary_sensor, states.sensor] %}
            {% for domain in domains %}
              {% for item in domain if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
                {% if (item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) %}
                  {{ item.name }}({{ item.attributes['battery_level'] }})
                {% endif %}
              {% endfor %}
            {% endfor %}
        data:
          device: iphone
          sound: spacealarm
          priority: 0
