# HomeKit Config
homekit:
  auto_start: false
  safe_mode: true
  filter:
    include_domains:
      - light
      - media_player
      - scene
      - switch
    exclude_entities:
      - light.all
      - light.hall_1
      - light.hall_2
      - media_player.sony_ht_nt5
      - switch.smart_plug_camera
      - switch.panic_light
      - scene.light_off_livingroom
      - scene.panic_light_off
      - scene.panic_light_on
    include_entities:
      - input_boolean.dfi
      - input_boolean.ott_club
      - input_boolean.kinopub
  entity_config:
    media_player.sony_bravia_tv:
      name: Зал Телевизор
      feature_list:
        - feature: on_off
    media_player.dunehd:
      name: Зал Дюна
      feature_list:
        - feature: on_off
    media_player.sony_htnt5:
      name: Зал Саундбар
      feature_list:
        - feature: on_off
    input_boolean.dfi:
      name: Зал Кинозал
    input_boolean.ott_club:
      name: Зал ОТТ Клуб
    input_boolean.kinopub:
      name: Зал Кинопаб
    switch.smart_plug_bedroom:
      name: Спальня Розетка
      type: outlet
    scene.bright_livingroom:
      name: Ярко
    scene.movie_livingroom:
      name: Кино
    scene.night_light_livingroom:
      name: Ночник


# Автоматизация
automation:
  # Задержка запуска HomeKit
  - alias: start_homeKit
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:01
      - service: homekit.start
